version: "3.8"

services:
  mongo:
    image: mongo:7.0
    container_name: ai_notes_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ai_notes_backend
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/ai-course-notes
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ai_notes_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo_data: